In [1]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator, array_to_img, img_to_array, load_img
import numpy as np

datagen = ImageDataGenerator(
        rotation_range=10,
        width_shift_range=0.2,
        height_shift_range=0.2,
        shear_range=0.2,
        zoom_range=0.2,
        horizontal_flip=True,
        fill_mode='nearest')
 
# use class_mode = 'sparse' , label will be 0 ,1,2,3,4

gener=datagen.flow_from_directory('images',
                                         batch_size=2,
                                         shuffle=True,
                                         class_mode='sparse')

def num_to_position(num):
    pos = []
    for i in range(5):
        pos.append( num % 2)
        num = num // 2
    return np.array(pos)

# 將 ImageDataGenerator產生的data or label 修改成自己想要的data or label format

def generator_wrapper(generator):
    for batch_x,batch_y in generator:
        y = []
        for num in batch_y:
            print(num)
            y.append(num_to_position(num))
        yield (batch_x,np.stack(y))


wrapped_generator = generator_wrapper(gener)

for i in range(10):
    datas, labels = next(wrapped_generator)
    print(datas.shape)
    print(labels.shape)
    for label in labels:
        print(label)


Found 66 images belonging to 6 classes.
3.0
3.0
(2, 256, 256, 3)
(2, 5)
[1. 1. 0. 0. 0.]
[1. 1. 0. 0. 0.]
5.0
5.0
(2, 256, 256, 3)
(2, 5)
[1. 0. 1. 0. 0.]
[1. 0. 1. 0. 0.]
0.0
5.0
(2, 256, 256, 3)
(2, 5)
[0. 0. 0. 0. 0.]
[1. 0. 1. 0. 0.]
2.0
4.0
(2, 256, 256, 3)
(2, 5)
[0. 1. 0. 0. 0.]
[0. 0. 1. 0. 0.]
1.0
0.0
(2, 256, 256, 3)
(2, 5)
[1. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]
2.0
3.0
(2, 256, 256, 3)
(2, 5)
[0. 1. 0. 0. 0.]
[1. 1. 0. 0. 0.]
0.0
3.0
(2, 256, 256, 3)
(2, 5)
[0. 0. 0. 0. 0.]
[1. 1. 0. 0. 0.]
2.0
4.0
(2, 256, 256, 3)
(2, 5)
[0. 1. 0. 0. 0.]
[0. 0. 1. 0. 0.]
5.0
0.0
(2, 256, 256, 3)
(2, 5)
[1. 0. 1. 0. 0.]
[0. 0. 0. 0. 0.]
0.0
0.0
(2, 256, 256, 3)
(2, 5)
[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]
